function res=trees(Z,fn,path)
% trees(Z,fn,path)
%   plots the trees of the processes in Z
%   the files are are saved as .fig and .jpg
%
%    The process Z is generated by bp.generate.process
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%   Z(4,:) - tree number - not required, defoult = 1
%
%   fn is the prefix of files
%   path is the path where the files will be stored

% Dimitar Atanasov, 2020
% datanasov@nbu.bg

[m,n] = size(Z);

if m == 3
    Z(4,:) = ones(1,n);
end;

T = unique(Z(4,:));
for t = T
    X = Z(:,find(Z(4,:) == t));
    h = bp.plot.treeplot(X([1 2 3],:),X(3,:),'k');
    title(['Tree ', num2str(t)]);
        fname = [path '\' fn num2str(t)];
        saveas(h,fname,'fig');
        saveas(h,fname,'jpg');
end;