function res=individual(Z)
% individual(Z)
%   returns the individual distribution estimator
%   for the process Z
%
%    The process Z is generated by bp.generate.process
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)


% Dimitar Atanasov, 2020
% datanasov@nbu.bg

Ch = bp.tools.countChilds(Z);
T = bp.tools.countPopulation(Z);
S = sum(T([1:length(T) - 1]));
for k = 1:length(Ch)
    res(k) = Ch(k)/S;
end;