function res = transformation(Z,dist,l1,l2,l3)
% transformation(Z,dist,l1,l2,l3)
%   returns the transformation of the
%   individual distribution which approximate
%   the normal distribution for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%
%   dist is theoretical distribution
%
%   l1,l2,l3 are additional parameters for the
%   theoretical distribution. Depends on the
%   distribution
%
%   The output paramater is the transformed
%   individual distribution

% Dimitar Atanasov, 2020
% datanasov@nbu.bg

%the individual distribution
Ind_D = bp.distribution.individual(Z);

%number ot particles inthe population
T = bp.tools.countPopulation(Z);

S = sum(T([1:length(T) - 1]));

K = 0:1:(length(Ind_D) - 1);

%The theoretical probabilities
if nargin == 3
    Pk = pdf(dist,K,ones(size(K)).*l1);
elseif nargin == 4
    Pk = pdf(dist,K,ones(size(K)).*l1,ones(size(K)).*l2);
elseif nargin == 5
    Pk = pdf(dist,K,ones(size(K)).*l1,ones(size(K)).*l2,ones(size(K)).*l2);
else
    error('Wrong number of input paramaters');
end;

res = S*((Ind_D - Pk)./sqrt((1-Pk).*Pk));