function res=HarrisEstTrees(Z)
% HarrisEstTrees(Z)
%   returns the Harris Estimator for the processes Z
%   for more than one tree.
%
%    The process Z is generated by bp.generate.multiType
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%   Z(4,:) - tree number


% Dimitar Atanasov, 2020
% datanasov@nbu.bg

if size(Z,1) < 4
    error('Wrong size of the input parameter Z. Try HarisEst!!!');
end;

Tr = unique(Z(4,:));
if length(Tr) == 1
    warning('There is only one tree. Better use HarisEst!!!');
end;

for t = Tr
    T = bp.tools.countPopulation(Z(1:3,find(Z(4,:) == t)));
    S_nom(t) = sum(T([2:length(T)]));
    S_den(t) = sum(T([1:length(T) - 1]));
end;

res = sum(S_nom)/sum(S_den);