function [l,q]=immigration(Z)
% immigration(Z)
%   returns the estimates of the immigrantion parameters for the process Z
%
%   The output is
%   l - the immigration mean
%   q - the immigrants distribution
%
%    The process Z is generated by bp.generate.process
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead, 3 - immigrant)


% Dimitar Atanasov, 2020
% datanasov@nbu.bg

t = 1:max(Z(2,:)); %each generation
Imgr = []; %immigrants

for k = t
    Imgr(k) = size(find(Z(2,:) == k & Z(3,:) == 3),2);
end;

m = max(t);
l = sum(Imgr)/m;

if ~isempty(Imgr)
    r = unique(Imgr);
    c = histc(Imgr,unique(Imgr));
end;

q = [];
for k = 1:size(r,2)
    q(r(k)+1) = c(k)/m;
end;
