function res=individualVarianceTrees(Z,m)
% individualVarianceTrees(Z)
%   returns the individual variance estimator
%   for the process Z  for more than one tree.
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%   Z(4,:) - tree number
%
%   m is the theoretical mean of the distribution
%     by default is the Harris estimator

% Dimitar Atanasov, 2020
% datanasov@nbu.bg

if size(Z,1) < 4
    error('Wrong size of the input parameter Z. Try individualVariance!!!');
end;

Tr = distinct(Z(4,:));
if length(Tr) == 1
    warning('There is only one tree. Better use individualVariance!!!');
end;

if nargin == 1
    m = bp.estimate.HarrisEstTrees(Z);
end;


Ind_D = bp.distribution.individualTrees(Z);

res = sum((((1:length(Ind_D)) - m).^2)*Ind_D');

