function res=individualVariance(Z,m)
% individualVariance(Z)
%   returns the individual variance estimator
%   for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%
%   m is the theoretical mean of the distribution
%     by default is the Harris estimator

% Dimitar Atanasov, 2020
% datanasov@nbu.bg

if nargin == 1
    m = bp.estimate.HarrisEst(Z);
end;

Ind_D = bp.distribution.individual(Z);

res = sum((((1:length(Ind_D)) - m).^2)*Ind_D');




