function res=LotkaNagaevEstTrees(Z)
% LotkaNagaevEstTrees(Z)
%   returns the Lotka- Nagaev Estimator for the processes Z
%   for more than one tree.
%
%    The process Z is generated by bp_gen_mt
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%   Z(4,:) - tree number


% Dimitar Atanasov, 2020
% datanasov@nbu.bg

if size(Z,1) < 4
    error('Wrong size of the input parameter Z. Try LotkaNagaevEst!!!');
end;

Tr = distinct(Z(4,:));
if length(Tr) == 1
    warning('There is only one tree. Better use LotkaNagaevEst!!!');
end;

for t = Tr
    T = bp.tools.countPopulation(Z(1:3,find(Z(4,:) == t)));
    if T(length(T)-1)==0
        res=1;
    else
        S_nom(t) = T(length(T));
        S_den(t) = T(length(T)-1);
    end;
end;

res = sum(S_nom)/sum(S_den);