function res=countPopulation(Z)
%  res=countPopulation(Z)
%    returns the population for the each generation
%    of the process Z generated by bp.generate.process
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%
% use distinct.m

% Dimitar Atanasov, 2020
% datanasov@nbu.bg

R = unique(Z(2,:));
res = [];

for g = R(find(R ~= 0))
    res(g) = length(find(Z(2,:) == g & Z(3,:) ~= 2));
end

